"""Inital migration

Revision ID: 62952e9616ad
Revises: 
Create Date: 2024-01-08 11:10:12.075157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62952e9616ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sudoku_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('initial_state', sa.String(length=81), nullable=False),
    sa.Column('final_state', sa.String(length=81), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('final_state'),
    sa.UniqueConstraint('initial_state')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sudoku_table')
    # ### end Alembic commands ###
